version: 0.0
os: linux
files:
  - source: scripts/geetagyan.org.conf
    destination: /etc/nginx/sites-available/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300